name: Pre-merge checks

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 2
      - name: Install 
        run: make install-deps
      - name: Run unit tests
        run: make test
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 2
      - name: Install 
        run: make install-deps-linux
      - name: Lint
        run: make lint